### ISSUE TITLE
Error when try to use synthetic pretrained model in notebook

### ISSUE THREAD

**Issue by Haodong-Alex-Yao** [cvg/SOLD2#10]
This might be a naive question. But it gives the following error when I try to use pretrained synthetic model in match_lines.ipynb:
                RuntimeError: Error(s) in loading state_dict for SOLD2Net:
	        Missing key(s) in state_dict: "w_desc", "descriptor_decoder.convPa.weight", "descriptor_decoder.convPa.bias", 
                "descriptor_decoder.convPb.weight", "descriptor_decoder.convPb.bias".

Is the structure of synthetic model different from wireframe model?

Regards,
Alex

**Comment by rpautrat** [comment]
Hi Alex,

The reason for this error is that the model pretrained on the synthetic dataset only contains the detector part and not the descriptor part. Thus it cannot be used directly in the notebook `match_lines.ipynb`.

One possibility would be to adapt the config file to the detector only, as is done in [`configs/train_detector.yaml`](https://github.com/cvg/SOLD2/blob/main/config/train_detector.yaml). Of course you will not be able to perform matching with this model since it doesn't have descriptors, but you can at least visualize the detected lines.

**Comment by Haodong-Alex-Yao** [comment]
Hi Remi,

Thanks for the clarification.

Regards,
Alex
