### ISSUE TITLE
How to watch rotation and translation and imshow results?

### ISSUE THREAD

**Issue by robotdevel** [cvg/SOLD2#18]
Hello author!

I love your project and thank you so much for sharing your program.

Now I am successful to run your program based on notebook source code.

But now I am using a docker system to run your python codes.

 Problems..

1. How can I get a rotation and translation from your matched lines?
 - I saw the cyon, pink and some colors from images with same position. But I don't know how I can get how much rotated or translated information?
 
2. How can I watch results in cv2.imshow?
  - I wanna know pixel information from your results: detected line(orange color) pixel level( pair),  matched line(pair, pixel-level)
  - for example, img1: orange(1,1) <-> img2: orange(3,3) if this is pair, than how can I know the pairs with pixel?

**Comment by rpautrat** [comment]
Hi!

Sorry for the late reply. I am not sure to fully understand your questions.

1. What rotation and translation are you talking about? Image rotation/translation, or the transformation from one line to another (different between each line)? In the latter case, simple geometry with lines should be enough. In the former case, there is no general rotation or translation if the pair of images are taken from different viewpoints, so the question is not very meaningful...

2. If I understand correctly, you want a match at a pixel level? The current algorithm only matches a full line segment, not at a pixel level. Since a matched segment might be occluded, there is no way to recover robustly which pixel should be assigned to which pixel in the second image. But maybe I misunderstood your question...

**Comment by robotdevel** [comment]
Hello author! 

Thank you so much to reply my questions.

I wanna try to develop the SLAM algorithm based on your method.

For example, if we have two images(a little bit different viewpoint change), your program already has functions to know the 3D rotation&translation values using your line descriptor?

Because I thought that it is possible to know rotation&translation if we find the descriptor matching results(I found this functions in superglue code, so I was curious you have that or not).

Best regards.

**Comment by rpautrat** [comment]
Hi,

I see, you meant relative camera rotation&translation.

The current code doesn't provide this functionality. To obtain the relative rotation&translation, SuperGlue is estimating the Essential matrix from the point matching (with cv2.findEssentialMat) and then extracting the relative rotation and translation from it.

As far as I know, there is no ready-made function doing the same with lines instead of points, but it is in theory possible to get the relative transformation from lines only. You can check out the following papers doing something similar for example:
- https://link.springer.com/article/10.1007/s11263-016-0971-9
- https://link.springer.com/article/10.1007/s00138-019-01012-0

**Comment by robotdevel** [comment]
Thank you so much.  It was very helpful!
