### ISSUE TITLE
Query for metric evaluation code

### ISSUE THREAD

**Issue by Jia-Wei-Liu** [cvg/SOLD2#27]
Hi! Thank you for sharing your codes!
You mentioned in the paper that you proposed two evaluation metrics to evaluate the line repeatability. Have you uploaded the metric evaluation code? I can't find the metric code in current repository. If not, do you have any plan to provide the evaluation metric code to public? Thank you very much!

**Comment by rpautrat** [comment]
Hi!
Indeed the evaluation code is not public yet, I needed to clean it a bit and make it easy to use. I have already promised to do it before, but I have not found the time to do it so far... So this should be added to this repo at some point, but I cannot guaranty that this will soon be the case.

**Comment by Jia-Wei-Liu** [comment]
Thank you for your quick reply! 
I understand your situation. In that case, could you please send me a rough uncleaned version of the metric evaluation code? Thank you very much!

**Comment by rpautrat** [comment]
Sure, I'll contact you privately.

**Comment by EchoTHChen** [comment]
I also need the evaluation code. Could you please send me this rough uncleaned version of the metric evaluation code? Thank you very much!

**Comment by rpautrat** [comment]
Have a look at this: https://github.com/cvg/SOLD2/issues/30#issuecomment-985026158

**Comment by EchoTHChen** [comment]
Thanks a lot!



---Original---
From: "Rémi ***@***.***&gt;
Date: Tue, Dec 7, 2021 19:02 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [cvg/SOLD2] Query for metric evaluation code (#27)




 
Have a look at this: #30 (comment)
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
