### ISSUE TITLE
How to filter out points/lines

### ISSUE THREAD

**Issue by AliButtar** [cvg/SOLD2#28]
Hello,

Thank you for the amazing repo. 

I am trying to filter out the lines that are detected on the edges of rectangular objects like windows, is there any way I can filter them out and just declutter all the ones in between. 

For example, if this is the image after inference: 

![image](https://user-images.githubusercontent.com/11333899/142176416-a6fd9c9d-e2ce-47f7-b2a5-a32541df3624.png)

I would like to get only these ones:

![image](https://user-images.githubusercontent.com/11333899/142176573-898db4a4-3d5e-4b22-844d-cb68f641e211.png)

If you can suggest some way where I can edit the configuration file to just detect the ones in the outer region and just get rid of all the ones in between that would be great. Please assume that there would be only the windows in the image, not the extra items you see on the left and the right such as the TV and the lamp.

Thanks,
AliButtar

**Comment by rpautrat** [comment]
Hi,
I don't think you can get what you want just by tuning parameters of the current version. I would rather have an object detector that defines what are the rectangular objects in your scene (because this is not even very well defined), and then based on these detections, manually suppress the lines inside such objects. But this requires of course a bit of work.

**Comment by AliButtar** [comment]
Let's say I do have an object detector that I can use to crop out the object of interest. Do you have any ideas on how I can work to suppress the lines inside the object? Any direction you can point me towards.

**Comment by rpautrat** [comment]
I suppose you can go through all lines and compute the intersection between the line and the object. If it exists, then you can remove the line. You would also need to define a threshold to accept intersections that are very close to the boundary of the object, so that you don't discard lines that are exactly on the boundary.
