### ISSUE TITLE
Qs about the paper

### ISSUE THREAD

**Issue by d5423197** [cvg/SOLD2#37]
Hello there,

I recently read your paper many times but still cannot understand the part (Descriptor Branch). When the network is doing a forward propagation. The network will go through homograph adaption to get the ground truth. Then the network will go through the backbone encoder and line detection module to get the predicted result. (junction and line heatmap). After that, the dense descriptor will compare these two results? If you can guide me to any prior knowledge, it will be appreciated. 

Thanks in advance,

Zhonghan Deng

**Comment by rpautrat** [comment]
Hi Zhonghan,

You are right that the homography adaptation is used to get the ground truth for the junction and line heatmaps.
For the descriptor branch, it is just an additional branch to the backbone network, not related to the two others. So there are three independent outputs of the network: junction heatmap, line heatmap, and dense descriptor.

Then at matching time, we take the output line segments and use them to sample the dense descriptor along each line segment. This is the only time when the two outputs line segments / descriptor are used in combination, otherwise they are independent.

I hope it is a bit clearer, let me know if not.

**Comment by d5423197** [comment]
Hello there,

Really appreciate your feedback. It is helpful.

Let us say we have a brand new data set.

The backbone: two outputs (junction, line heatmap)
The network: three outputs (junction, line heatmap, dense descriptors)

1. The dataset will be fed into the backbone to get all the ground truth. (homography adaptation)
2. Then the dataset will be fed into the network to predict and compare the predicted result with ground truth from 1.

I dont know when we use descriptor branch. Do we use it at inferencing? (according to the paper, i thought we only use the other two branches)

**Comment by rpautrat** [comment]
Ah, I think I understand you confusion. In the paper, backbone refers to the shared weights at the beginning of the network, before being split into junction, heatmap and descriptor branches.

There is only one network actually, it is the same used to generate the ground truth and to do the training/inference. But we re-train this same network several times in a row.

If I recap the different steps:
- the network (junctions and heatmap) is trained a first time on the synthetic dataset with ground truth (GT) data.
- the trained network is used together with homographic adaptation to generate the pseudo GT on real images.
- the network is retrained on the real images (junctions, heatmap and descriptor this time), using the previously generated pseudo GT.

The descriptor is not included in the first step because we only want to train the descriptor on real images so we don't care about it on synthetic images. Then at inference time, the three outputs junctions, line heatmap and descriptors are used.

**Comment by d5423197** [comment]
Hello there,

Thanks for your feedback. I will reread the paper with these explanation.

Best,

Zhonghan Deng

**Comment by d5423197** [comment]
Hello there,

Thanks for your kindly explanation. I have read SOLD and SuperPoint. I am still confused about the descriptor. I dont know why we need it for inferencing. We already hafve junctions and line heatmap which can generate the line segmentation. Could you please explain the usage of the descriptor?

**Comment by rpautrat** [comment]
Hi, the descriptor is used to match lines across images. It is a way to uniquely describe each line segment and to recognize them in other images later. Without descriptors, it would be impossible to know which segments have moved where when we capture the scene under a novel viewpoint.

If you look at the videos in the Readme, the detector is basically detecting the line segments, and the descriptor is then used to put the same color on the lines on the two frames of the video.

**Comment by d5423197** [comment]
Hello there,

Are there any papers or sth that you recommend me to read if i want to learn the descriptor part in detail? I understand the junction and the line heatmap part of the architecture. What do you mean by matching lines? If we input one image, why do we have to match lines across images?

**Comment by d5423197** [comment]
Hello there,

For the line matching part, i understand the forward pass of Needleman-Wunsch  algo. But I could not understand how the algo find the optimal path. Where can I find the detail for that part?

**Comment by rpautrat** [comment]
Hi,

When I say matching lines, it requires indeed at least two images where you want to recognize which images are the same. It does not make sense for a single image.

Line description is a follow-up of point description, which has been studied for years in computer vision. I guess you can find more about it in any computer vision book. Or you can also have a look at the OpenCV tutorials on the topic: https://docs.opencv.org/4.x/db/d27/tutorial_py_table_of_contents_feature2d.html.

To understand better the Needleman-Wunsch algo, you may check the Wikipedia page, this might be better explained than in the SOLD² paper: https://en.wikipedia.org/wiki/Needleman%E2%80%93Wunsch_algorithm

**Comment by d5423197** [comment]
Hi there,

Thanks for your reply. The graph from the paper shows the input for the 3rd step training is one image. So the input for 3rd part should be 2 images? One is the original image, the other is warp image? If the input is one image, the descriptor has no way to be trained. 

Question is: the descriptor part in the paper says given two images and matched lines. How can you get the matched lines from these two images when training?

**Comment by rpautrat** [comment]
Hi,

There is no descriptor in steps 1 to 4, and a single input image is enough in these steps. The descriptor is only trained in step 5, with pairs of images. We generate the image pairs ourselves with a synthetic homographic warp of the reference image. Thus we can get the ground truth matches by applying the homography on the lines to warp them from the reference image to the warped version.

**Comment by rpautrat** [comment]
I hope this clarified your understanding of the paper. I am closing this now, but feel free to reopen it if you have more questions.
