### ISSUE TITLE
Pre-trained model in step2

### ISSUE THREAD

**Issue by xuyongzhi** [cvg/SOLD2#4]
In step 2, while generating raw pseudo ground truth, the pre-trained model using the synthetic dataset is used. Does it help to use the final pre-trained model using the wireframe dataset, or other pre-trained models of other methods (e.g. TP-LSD, HAWP).

**Comment by brade31919** [comment]
Hi @xuyongzhi ,

The quality of the pseudo ground truth might be slightly better by using the final pre-trained model, but the fact is that the final pre-trained model is also produced by this whole pipeline. Therefore, it's similar to just perform the self-supervised process (homography adaptation) more times.

Yeah it's also possible to bootstrap other existing methods for potentially better pseudo ground truth. However, the whole pipeline  will not be self-supervised then because theses methods (HAWP, TP-LSD, etc.) were trained by the ground truth line segments. If the goal is to extract pseudo ground truth on other datasets (not wireframe), then it's possible to generate them from other existing models as long as you have a method to extract GT line segments from their aggregated predictions.

Best

**Comment by xuyongzhi** [comment]
HI @brade31919 ,
Thanks for your prompt and detailed reply!
About this idea  

> as long as you have a method to extract GT line segments from their aggregated predictions.

If I use wireframe pre-trained model or TP-LSD while generating GTs on Holicity or some other datasets, do you mean that I should post-process the detection before using as GT. The prediction output of "SODL2 wireframe pre-trained model" or TP-LSD may contain some bad detections that should not be used as GT.  Does the self-supervision pipeline can handle the false positive detections itself. Or some pre-processing of cleaning the detection beforing to be used as GT is necessary?

Thanks!

**Comment by xuyongzhi** [comment]
Hi @brade31919 ,
Thanks for sharing the great work again!

I have another open question about line instance definition (shortest VS longest). 
I found that SOLD2 is likely to detect one long line segment as several colinear and connected short sub-line segments. It does work to simply merge the sub-lines together in the post-processing. However, I am wondering would it bring any benefits to directly detect long line instances. For instance, the GT generation can be merged in the longest line instance format. (Hope I have described the problem clear 😂)
1) Is longer lines more robust than short lines in terms of repeatability;
2) The total number of lines will be much smaller
Especially, very short lines may be very difficult to accurately detect and also hard be used in other applications.

Thanks!
All the best!

**Comment by brade31919** [comment]
Hi @xuyongzhi 

Yes, that step is very critical to our self-supervised pipeline. You can find some details in [section 3.4 and figure 2 in our paper](https://arxiv.org/pdf/2104.03362.pdf), or you can refer to [section 5 and figure 5 in Superpoint](https://arxiv.org/pdf/2104.03362.pdf) for more details. Basically, we separate our predictions into (1) junction probability, and (2) line heatmap probability because we can perform warping and aggregation on these probability maps. However, it's not clear for methods like LCNN to perform this step because applying LOI pooling and the detection module on the aggregated feature tensors might not give you better results.

In our method, we actually keep the long line segments and their sub-segments because they are all "line segments" (but not necessarily wireframes). According to our experiments, long line segments are not more robust than short lines because they are easily occluded from viewpoint changes. Although we design our matching method to be more robust to these occlusion, it's still challenging under some extreme cases. In fact, the best line segments are those segments with medium lengths :joy: 

Best

**Comment by xuyongzhi** [comment]
Hi @brade31919 ,

Really appreciate your nice and deep elaboration! 
It is very interesting that you found lines with medium lengths are better 😉 
Keeping both long segments and their sub-segments is a smart idea 👍 Will learn from your codes later.
Thanks!
