### ISSUE TITLE
Speed up inference time

### ISSUE THREAD

**Issue by d5423197** [cvg/SOLD2#56]
Hello Author:

I want to use this algorithm in a CPU environment. Currently, I used the pre-trained weights, the inference time is about 15- 20s per image. I am wondering if I just use the line detection model, will it be faster a lot? (I mean the model which does not have the descriptor head) Because I do not need the descriptor part. 

Any advice will be appreciated. 

Best

**Comment by rpautrat** [comment]
Hi,

Yes, removing the descriptor part will speed up quite a lot I think, because the matching with Needleman-Wunsch is not so well optimized for now.

But if you really want to use it on CPU, I would recommend changing the backbone and retraining the network. For example using a MobileNet architecture or one of its follow-up works.

**Comment by d5423197** [comment]
Hello there,

Thanks for your advice. I will definitely try that. Appreciate it!

ZD
