### ISSUE TITLE
Training on KITTI dataset

### ISSUE THREAD

**Issue by qiaozhijian** [cvg/SOLD2#63]
I have referred to #19 and trained the model successfully. But the size of KITTI images is 1408*376, which is quite different from the default size of 512*512. 

1. Cound you please provide any suggestion on data preprocessing configuration like "resize"? 
2. For "blur_size", wouldn't a sharper picture result in more accurate line features? Why do we need to apply Gaussian filtering to the image?

Looking forward to your reply, thank you!

**Comment by rpautrat** [comment]
It seems that the images in KITTI are quite large because of a wide field of view, but the resolution might still be reasonable for SOLD2. So you could try running it directly without any resize.

The parameter "blur_size" was only used in the synthetic dataset, to make the images a bit more realistic and more smooth. So it is actually more to make the prediction harder for the network than the opposite. Apart from the synthetic dataset, the "blur_size" is never used.

**Comment by qiaozhijian** [comment]
Thank you. It answers my question.
